apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-trends-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-trends
  template:
    metadata:
      labels:
        app: devops-trends
    spec:
      containers:
        - name: devops-trends
          image: admintita/devops-trends-app:v25
          ports:
            - containerPort: 8080